### ISSUE TITLE
Mixed language in "About" page

### ISSUE THREAD

**Issue by G07cha** [MathMark/PlotBuilder#1]
As on screen shot, window name and version writen on Russian language but another stuff is on Engilsh better be if all labels have English localisation

![default](https://cloud.githubusercontent.com/assets/6943514/9568810/6c906de2-4f5e-11e5-825d-21bbe935db3a.png)

**Comment by MathMark** [comment]
Corrected

**Comment by G07cha** [comment]
@MathMark, please [reference](https://guides.github.com/features/issues/#notifications) this issue to commit where this issue resolved

**Comment by MathMark** [comment]
488dc4628b3eea719d15b32fdc8f8f2d4f9f05a6
