### ISSUE TITLE
Rebuilding same function

### ISSUE THREAD

**Issue by G07cha** [MathMark/PlotBuilder#6]
Add check is same function rebuiling or just block 'Build' button until textfield with function don't be changed becouse multiple building will cause to incorrect function fiew(second graphic)
![default](https://cloud.githubusercontent.com/assets/6943514/9586259/5d402956-5024-11e5-89c0-b9f17dcd1c12.png)

**Comment by MathMark** [comment]
72bc78d7d51935db7d808917b08a69a32a70755f

**Comment by MathMark** [comment]
This concern was solved by overriding Equals() and GetHashCod() functions
